### PR TITLE
graph 1.0

### PR DESCRIPTION
**Pull request by spaceturtleturtle**
I hope this works?

### CODE REVIEW

**Comment by spaceturtleturtle** [comment]
I don't actually know, probably because of npm audit fix? 
How should I resolve this?

**Comment by RunDevelopment** [comment]
> probably because of npm audit fix?

Probably not. A few dependencies have been upgraded (new major version) and `npm audit fix` wouldn't do that AFAIK.

> How should I resolve this?

That's the difficult part... The easiest way would probably be to reset `package.json` and `package-lock.json` (no git fu here, just copynpaste the contents from master), run `npm ci`, and then install your necessary new dependencies.

**Comment by RunDevelopment** [comment]
@spaceturtleturtle Also, a little tip: You should probably get the ESLint extension for your IDE (e.g. [this one](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for VSCode). This will allow you IDE to find errors and auto-format your code. Makes it easy to write (correct) code.

**Comment by RunDevelopment** [comment]
I just noticed this: Why do you have a branch (`graph`) in this repo AND a fork? Why not just use the branch?

**Comment by spaceturtleturtle** [comment]
I only created the graph branch recently as a destination for the fork. 

I followed your suggestions to fix package/install ESLint. 
If you have no objections, I'll merge the fork into the branch.

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
After you merged your fork, I suggest making another PR from `graph` into `master`. 

You'll get CI that way and it's really useful to have something constantly checking your code.

**Pull request merged**
